use core:debug;

void errorOn(Int point, Int now) {
	if (point == now)
		throwError;
}

// Make sure the cleanup runs properly at various points in the function.
void basicException(Int point) {
	errorOn(point, 1);
	DbgVal a(5);
	{
		errorOn(point, 2);
		Dbg d(20);
		errorOn(point, 3);
		DbgVal v(10);
		errorOn(point, 4);
	}
	errorOn(point, 5);
	{
		DbgVal v(6);
		errorOn(point, 6);
	}
	errorOn(point, 7);
}

// How do we do with exceptions in other functions.
void fnException(Int point) {
	errorOn(point, 1);
	DbgVal r = dbgValFn(DbgVal(1), point);
	errorOn(point, 3);
}

DbgVal dbgValFn(DbgVal v, Int point) {
	errorOn(point, 2);
	v.set(3);
	v;
}

// How do we do with exceptions combined with thread switches?
void threadException(Int point) {
	errorOn(point, 1);
	DbgVal r = otherThreadError(DbgVal(1), point);
	errorOn(point, 4);
}

// Thread function for another thread.
DbgVal otherThreadError(DbgVal p, Int point) on Other {
	errorOn(point, 2);
	p.set(2);
	errorOn(point, 3);
	p;
}
